//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int OrderID { get; set; }
        public int OrderProductId { get; set; }
        public int OrderProductCount { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int OrderPickupPointId { get; set; }
        public Nullable<int> OrderUserId { get; set; }
        public string OrderPickupCode { get; set; }
        public int OrderStatusId { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Pickpoints Pickpoints { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
